name: github pages
on:
  workflow_dispatch:
  push:
    branches:
      - main # default branch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.19.3
        uses: actions/setup-node@v2
        with:
          node-version: "14.19.3"
      - name: Install Dep
        run: yarn
      - name: Build
        run: npm run build
      - name: Deploy
#        uses: peaceiris/actions-gh-pages@v3
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          publish_dir: ./docs/.vuepress/dist
